[package]
name = "lapce"
version = "0.0.10"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2021"
resolver = "2"

[dependencies]
lapce-ui = { path = "./lapce-ui" }
lapce-proxy = { path = "./lapce-proxy" }

[[bin]]
name = "lapce"
path = "lapce-ui/src/bin/lapce.rs"

[[bin]]
name = "lapce-proxy"
path = "lapce-proxy/src/bin/lapce-proxy.rs"

[workspace]
members = ["lapce-ui", "lapce-proxy", "lapce-rpc", "lapce-data", "lapce-core"]
