[package]
name = "lapce-core"
version = "0.0.10"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2021"

[dependencies]
itertools = "0.10.3"
serde_json = "1.0"
tree-sitter = "0.20.6"
tree-sitter-rust = "0.20.0"
xi-rope = { git = "https://github.com/lapce/xi-editor", features = ["serde"] }
